# Created by trellis-cli v0.9.2
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  hpecology.co.uk:
    site_hosts:
      - canonical: hpecology.co.uk
        redirects:
          - www.hpecology.co.uk
    local_path: ../site
    branch: bugfix/template-selection
    repo: git@github.com:willnjl/hpecology.co.uk.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
